{{- if .Values.ingressHost }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ template "hmcts.releaseName" . }}
  labels:
    app.kubernetes.io/name:  {{ template "hmcts.releaseName" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance:  {{ template "hmcts.releaseName" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName:  {{ template "hmcts.releaseName" . }}
          servicePort: 80
{{- end}}